### ISSUE TITLE
Not Building Projections

### ISSUE THREAD

**Issue by Rastlore30** [SKO85/SE-Mods-Nanobot-Build-And-Repair-System#2]
So I ran this mod after removing the original BaRs, (due to it not welding projections, only grind and collection functionality), only to find this mod is now suffering the same fate after two days of use.  It will no longer build projections but the other functions work as designed.  Currently on the world I am testing this on I only have Colorful Icons, Build Vision, Build Info, HUD Remastered, and Text HUD API installed.  This is the only mod that adds a block to the world.

**Comment by SKO85** [comment]
@Rastlore30
Have you tried to fully remove the previous mod to make sure you only use my version? Is this on a multiplayer server or local game play?

**Comment by SKO85** [comment]
Has been solved. Contacted Restlore30 via Steam.
